version: '3.8'

networks:
  laravel:
  rabbitmq:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8088:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'mabbit'
    container_name: rabbitmq_management
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./src:/var/lib/rabbitmq/mnesia/"
    restart: always
    networks:
      - rabbitmq

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: jvconsult
      MYSQL_USER: root
      MYSQL_PASSWORD: arthur
      MYSQL_ROOT_PASSWORD: arthur
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    working_dir: /var/www
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
    ports:
      - 8000:8000
    depends_on:
      - mysql
